In [1]:
import pandas as pd

raw = pd.read_csv('datasets/fifa_22_preprocessed.csv')
raw.head()

,Unnamed: 0,Name,Age,Height,Weight,Overall,Potential,Growth,TotalStats,BaseStats,...,BestPosition_GK,BestPosition_LB,BestPosition_LM,BestPosition_LW,BestPosition_LWB,BestPosition_RB,BestPosition_RM,BestPosition_RW,BestPosition_RWB,BestPosition_ST
0,0,L. Messi,34,170,72,93,93,0,2219,462,...,0,0,0,0,0,0,0,1,0,0
1,1,R. Lewandowski,32,185,81,92,92,0,2212,460,...,0,0,0,0,0,0,0,0,0,1
2,2,Cristiano Ronaldo,36,187,83,91,91,0,2208,457,...,0,0,0,0,0,0,0,0,0,1
3,3,K. Mbappé,22,182,73,91,95,4,2175,470,...,0,0,0,0,0,0,0,0,0,1
4,4,J. Oblak,28,188,87,91,93,2,1413,489,...,1,0,0,0,0,0,0,0,0,0

In [2]:
raw.shape

(19260, 92)

In [3]:
data = raw.drop(['Unnamed: 0', 'Name', 'Club'], axis=1)

In [4]:
data.head()

,Age,Height,Weight,Overall,Potential,Growth,TotalStats,BaseStats,ValueEUR,WageEUR,...,BestPosition_GK,BestPosition_LB,BestPosition_LM,BestPosition_LW,BestPosition_LWB,BestPosition_RB,BestPosition_RM,BestPosition_RW,BestPosition_RWB,BestPosition_ST
0,34,170,72,93,93,0,2219,462,78000000,320000,...,0,0,0,0,0,0,0,1,0,0
1,32,185,81,92,92,0,2212,460,119500000,270000,...,0,0,0,0,0,0,0,0,0,1
2,36,187,83,91,91,0,2208,457,45000000,270000,...,0,0,0,0,0,0,0,0,0,1
3,22,182,73,91,95,4,2175,470,194000000,230000,...,0,0,0,0,0,0,0,0,0,1
4,28,188,87,91,93,2,1413,489,112000000,130000,...,1,0,0,0,0,0,0,0,0,0

In [5]:
y = data['ValueEUR']

In [6]:
#all predictors
#X = data.drop(['ValueEUR'], axis=1)

In [7]:
#realistic predictors 1
#features = ['Age', 'Height', 'Weight', 'ClubJoined', 'LeftFoot']

#realistic predictors 2
""""features = ['Age', 'Height', 'Weight', 'ClubJoined', 'LeftFoot', 'BestPosition_CB', 'BestPosition_CDM', 'BestPosition_CF',
       'BestPosition_CM', 'BestPosition_GK', 'BestPosition_LB',
       'BestPosition_LM', 'BestPosition_LW', 'BestPosition_LWB',
       'BestPosition_RB', 'BestPosition_RM', 'BestPosition_RW',
       'BestPosition_RWB', 'BestPosition_ST']"""

#realistic predictors 3
features = ['Age', 'Height', 'Weight', 'ClubJoined', 'LeftFoot', 'BestPosition_CB', 'BestPosition_CDM', 'BestPosition_CF',
       'BestPosition_CM', 'BestPosition_GK', 'BestPosition_LB',
       'BestPosition_LM', 'BestPosition_LW', 'BestPosition_LWB',
       'BestPosition_RB', 'BestPosition_RM', 'BestPosition_RW',
       'BestPosition_RWB', 'BestPosition_ST', 'IntReputation', 'WeakFoot', 'SkillMoves',
       'AttackingWorkRate', 'DefensiveWorkRate']

In [8]:
data.columns

Index(['Age', 'Height', 'Weight', 'Overall', 'Potential', 'Growth',
       'TotalStats', 'BaseStats', 'ValueEUR', 'WageEUR', 'ReleaseClause',
       'ClubJoined', 'LeftFoot', 'IntReputation', 'WeakFoot', 'SkillMoves',
       'AttackingWorkRate', 'DefensiveWorkRate', 'PaceTotal', 'ShootingTotal',
       'PassingTotal', 'DribblingTotal', 'DefendingTotal', 'PhysicalityTotal',
       'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys',
       'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance',
       'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes', 'STRating',
       'LWRating', 'LFRating', 'CFRating', 'RFRating', 'RWRating', 'CAMRating',
       'LMRating', 'CMRating', 'RMRating', 'LWBRating', 'CDMRating',
       'RWBRating', 'LBRating', 'CBRating', 'RBRating', 'GKRating',
       'BestPosition_CB', 'BestPosition_CDM', 'BestPosition_CF',
       'BestPosition_CM', 'BestPosition_GK', 'BestPosition_LB',
       'BestPosition_LM', 'BestPosition_LW', 'BestPosition_LWB',
       'BestPosition_RB', 'BestPosition_RM', 'BestPosition_RW',
       'BestPosition_RWB', 'BestPosition_ST'],
      dtype='object')

In [9]:
X = data[features]

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=0)

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

model = RandomForestRegressor(n_estimators=100, random_state=0)

my_pipeline = Pipeline(steps=[('model', model)])

my_pipeline.fit(X_train, y_train)

preds = my_pipeline.predict(X_test)

score = mean_absolute_error(y_test, preds)
print('MAE:', score)

MAE: 1977132.1513698513

In [ ]:
#MAE from all predictors: 188646.62906801663
#MAE from realistic predictors1: 3548295.4893421163
#MAE from realistic predictors2: 3497911.793490102  ##!! knowing position didn't make a difference
#MAE from realistic predictors3: 1977132.1513698513